# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instockbill',
            name='InStockBillCode',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='instockbill',
            name='Operator',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
